name: Build and Release SharpHunter

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Compile
        working-directory: SharpHunter
        run: |
          msbuild SharpHunter.sln /p:Configuration=Release

      - name: Verify Build Output
        working-directory: SharpHunter
        shell: powershell
        run: |
          $exePath = "bin/Release/SharpHunter.exe"
          if (-Not (Test-Path -Path $exePath)) {
            Write-Error "Build output $exePath not found."
            exit 1
          }
          Write-Output "$exePath found successfully."

      - name: Patch Runtime Version to v4.0.30319
        shell: pwsh
        run: |
          $exePath = "./SharpHunter/bin/Release/SharpHunter.exe"
          $ilPath = "./SharpHunter/bin/Release/SharpHunter.il"
          $newIlPath = "./SharpHunter/bin/Release/SharpHunter_new.il"
          $resPath = "./SharpHunter/bin/Release/SharpHunter.res"

          $vswhere = "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe"
          $vsPath = & $vswhere -latest -property installationPath
          Import-Module "$vsPath\Common7\Tools\Microsoft.VisualStudio.DevShell.dll"
          Enter-VsDevShell -VsInstallPath $vsPath -SkipAutomaticLocation

          echo "Disassembling $exePath..."
          ildasm $exePath /out=$ilPath

          echo "Patching IL file to target .NET Runtime v4.0.30319..."
          (Get-Content $ilPath) -replace 'RuntimeVersion "v2.0.50727"', 'RuntimeVersion "v4.0.30319"' | Set-Content $newIlPath

          echo "Reassembling executable..."
          if (Test-Path $resPath) {
            ilasm $newIlPath /output=$exePath /resource=$resPath /quiet
          } else {
            ilasm $newIlPath /output=$exePath /quiet
          }
          echo "Patching complete."

      - name: Copy exe to BOF folder
        working-directory: SharpHunter
        shell: powershell
        run: |
          Copy-Item -Path "bin/Release/SharpHunter.exe" -Destination "BOF" -Force
          Write-Output "SharpHunter.exe copied to BOF folder."

      - name: Install 7-Zip PowerShell Module
        shell: powershell
        run: |
          Install-Module 7Zip4PowerShell -Force -Verbose

      - name: Build Artifact (ZIP)
        working-directory: SharpHunter
        shell: powershell
        run: |
          $outputZip = "${{ github.workspace }}/SharpHunterBOF.zip"
          if (Test-Path -Path $outputZip) {
            Remove-Item -Path $outputZip -Force
            Write-Output "Old zip file removed."
          }
          Compress-7Zip -Path "BOF" -ArchiveFileName $outputZip -Format Zip
          Write-Output "Artifact created at $outputZip"

      - name: Delete old tag and release
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          delete_release: true
          tag_name: AutoBuild
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: AutoBuild
          release_name: "SharpHunter AutoBuild"
          body: "Automated build and release of SharpHunter."
          draft: false
          prerelease: false

      - name: Upload EXE to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: SharpHunter/bin/Release/SharpHunter.exe
          asset_name: SharpHunter.exe
          asset_content_type: application/octet-stream

      - name: Upload ZIP to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: SharpHunterBOF.zip
          asset_name: SharpHunterBOF.zip
          asset_content_type: application/zip
